language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - frontend/node_modules
    - backend/node_modules

# addons:
#   chrome: stable

script:
  - cd frontend
  - npm run lint
  - npm install
  - npm run build
  # - npm run test:headless
  # - ng build --aot
  # - xvfb-run npm run e2e
  - cd ../backend
  - npm run lint
  - npm install
  - npm run build

notifications:
  email: false
