language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm install
  # - npm run test:headless
  # - npm run build
  # - ng build --aot
  # - xvfb-run npm run e2e
